Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,6 +41,10 @@ jobs:
         run: |
           docker-compose run --rm backend npm run coverage
 
+      - name: Debug Coverage Directory
+        run: |
+          docker-compose exec backend ls -R /usr/src/app/coverage || echo "Coverage directory not found!"
+
       - name: Upload Coverage to Codecov
         run: |
           docker-compose exec backend npx codecov --file=/usr/src/app/coverage/lcov.info --disable=gcov
