fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,17 +13,17 @@ jobs:
     runs-on: ubuntu-latest
 
     env:
-      DB_USERNAME: 'healtcare_db_user'
-      DB_PASSWORD: '1lNR2y84HYyEftDx0Ha5ZuMtyV8Puyrv'
-      DB_DATABASE: 'healthub_db'
-      DB_HOST_PORT: '5432'
-      API_HOST_PORT: '4000'
-      API_CONTAINER_PORT: '4000'
-      APP_HOST_PORT: '3000'
-      ENV: 'staging'
-      API_JWT_SECRET: '123password'
-      API_URL: 'http://localhost:4000'
-      DB_HOST: 'db'
+      DB_USERNAME: "healtcare_db_user"
+      DB_PASSWORD: "1lNR2y84HYyEftDx0Ha5ZuMtyV8Puyrv"
+      DB_DATABASE: "healthub_db"
+      DB_HOST_PORT: "5432"
+      API_HOST_PORT: "4000"
+      API_CONTAINER_PORT: "4000"
+      APP_HOST_PORT: "3000"
+      ENV: "staging"
+      API_JWT_SECRET: "123password"
+      API_URL: "http://localhost:4000"
+      DB_HOST: "db"
 
     steps:
       - name: Checkout Repository
@@ -37,23 +37,23 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y docker-compose
 
-      - name: Build Docker Services
-        run: |
-          docker-compose down
-          docker-compose -f docker-compose.yml build
-
       - name: Run Backend Tests with Coverage
         run: |
           docker-compose run --rm backend npm run coverage
 
+      - name: Copy Coverage to Host
+        run: |
+          mkdir -p backend/coverage
+          docker cp $(docker-compose ps -q backend):/usr/src/app/coverage/lcov.info backend/coverage/lcov.info
+
       - name: Debug Coverage Directory
         run: |
-          ls -R coverage || echo "Coverage directory not found!"
+          ls -R backend/coverage || echo "Coverage directory not found!"
 
       - name: Upload Coverage to Codecov
         run: |
-          npx codecov --file=coverage/lcov.info --disable=gcov
-        env:
+          npx codecov --file=backend/coverage/lcov.info --disable=gcov
+          env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
 
       - name: Deploy Services
